;;; omarchy-colors.el --- Generated by Omarchy theme system -*- lexical-binding: t -*-
;;; Do not edit - this file is regenerated when you change themes.

(setq omarchy-color-accent "{{ accent }}")
(setq omarchy-color-cursor "{{ cursor }}")
(setq omarchy-color-fg "{{ foreground }}")
(setq omarchy-color-bg "{{ background }}")
(setq omarchy-color-sel-fg "{{ selection_foreground }}")
(setq omarchy-color-sel-bg "{{ selection_background }}")

(setq omarchy-color-black "{{ color0 }}")
(setq omarchy-color-red "{{ color1 }}")
(setq omarchy-color-green "{{ color2 }}")
(setq omarchy-color-yellow "{{ color3 }}")
(setq omarchy-color-blue "{{ color4 }}")
(setq omarchy-color-magenta "{{ color5 }}")
(setq omarchy-color-cyan "{{ color6 }}")
(setq omarchy-color-white "{{ color7 }}")
(setq omarchy-color-bright-black "{{ color8 }}")
(setq omarchy-color-bright-red "{{ color9 }}")
(setq omarchy-color-bright-green "{{ color10 }}")
(setq omarchy-color-bright-yellow "{{ color11 }}")
(setq omarchy-color-bright-blue "{{ color12 }}")
(setq omarchy-color-bright-magenta "{{ color13 }}")
(setq omarchy-color-bright-cyan "{{ color14 }}")
(setq omarchy-color-bright-white "{{ color15 }}")

(provide 'omarchy-colors)
;;; omarchy-colors.el ends here
